function obj = save_to_db(obj, temperature, chi, N, convergence, C, T)
  if obj.SAVE_TO_DB
    sqlite3.execute(obj.db_id,  ...
      'INSERT INTO tensors (temperature, chi, n, convergence, c, t, initial) VALUES (?, ?, ?, ?, ?, ?, ?)', ...
      temperature, chi, N, convergence, getByteStreamFromArray(C), getByteStreamFromArray(T), ...
      obj.initial_condition);
    fprintf(['stored to database: \n' ...
      'temperature = ' num2str(temperature) ...
      ', chi = ' num2str(chi) ...
      ', N = ' num2str(N) ...
      ', convergence = ' num2str(convergence) ...
      ', initial = ' obj.initial_condition '\n'])
  end
end
