function obj = save_to_db(obj, temperature, chi, N, convergence, C, T, truncation_error)
  query = ['INSERT INTO tensors (temperature, chi, n, convergence, c, t, initial, q, truncation_error)' ...
      ' VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)'];
  if obj.SAVE_TO_DB
    sqlite3.execute(obj.db_id,  query, ...
      temperature, chi, N, convergence, getByteStreamFromArray(C), getByteStreamFromArray(T), ...
      obj.initial_condition, obj.q, truncation_error);
    fprintf(['stored to database: \n' ...
      'temperature = ' num2str(temperature) ...
      ', chi = ' num2str(chi) ...
      ', N = ' num2str(N) ...
      ', convergence = ' num2str(convergence) ...
      ', initial = ' obj.initial_condition ...
      ', q = ' num2str(obj.q) ...
      'truncation error = ' num2str(truncation_error) '.\n'])
    % prevent matlab from crashing? :(
    fclose('all');
  end
end
